### **Import Numpy**
*  NumPy's core object is the ndarray, which stands for an N-dimensional array. It is a powerful, homogeneous multidimensional container used for fast mathematical operations in Python

![Picturess1.png](./assets/image.png)

In [2]:
import numpy as np

### **Why is NumPy faster than standard Python lists?**

* Fixed Data Types and Smaller Memor - NumPy uses fixed types (such as int32, int16, or int8), storing data compactly. Standard Python lists store full built-in int objects that require additional memory to track object values, object types, reference counts, and size. Because NumPy uses far fewer bytes of memory, the computer reads and processes the data much quicke
* No Type Checking During Iteration
* Contiguous Memory Allocation:
![Picturess1.png](./assets/memory.png)


### **Basics**

In [3]:
x=np.array([1, 2, 3, 4, 5],dtype=np.int16)
print(x)

[1 2 3 4 5]


In [4]:
y = np.array([[1,2,3,4],
              [5,6,7,8]])
print(y)

[[1 2 3 4]
 [5 6 7 8]]


In [5]:
#get dimensions

y.ndim

2

In [6]:
#get shape
y.shape

(2, 4)

In [7]:
#data type
print(x.dtype)
print(y.dtype)

int16
int64


In [8]:
#get size

x.itemsize

2

In [9]:
#get total size
x.size

5

### **Accesing/Changing specif elements,rows,columns,etc**

In [22]:
a = np.array([[1,2,3,4,5,6,7],
             [8,9,10,11,12,13,14]])

print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [23]:
#get a specific element [r,c]
#want to get 11
print(a[1,3])

#want to get 14
print(a[1,6])

11
14


In [28]:
#get a specific row
#want to get 1'st row

print(a[0])

#want to get 2nd row
print(a[1])

[1 2 3 4 5 6 7]
[ 8  9 10 11 12 13 14]


In [33]:
#get a specic column

#want to get 3rd column

print(a[:,2])

#want to get last column
print(a[:,6])

[ 3 10]
[ 7 14]


In [35]:
#getting a specific numbers that you want(in contiguouse)

#want to get numbers between 9 -13
a[1,1: 1:6]

array([], dtype=int64)

In [36]:
#change elements
a[0,1] =10
print(a)

[[ 1 10  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [37]:
#change a entire row by 1 number
a[0,:]=10
print(a)

[[10 10 10 10 10 10 10]
 [ 8  9 10 11 12 13 14]]


In [38]:
#want to change row by specific numbers
a[0,:]=[1,2,3,4,5,6,7]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [40]:
#Want to change specific column by one number
a[:,5]=6
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12  6 14]]


In [44]:
#Want to change column by specific numbers
a[:,5]=[6,13]
a[:,6]=[7,14]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
